set(_CATKIN_CURRENT_PACKAGE "rb1m_moveit_config")
set(rb1m_moveit_config_VERSION "0.3.0")
set(rb1m_moveit_config_MAINTAINER "Esau Escobar <eej@uaem.mx>")
set(rb1m_moveit_config_PACKAGE_FORMAT "1")
set(rb1m_moveit_config_BUILD_DEPENDS "rb1_description")
set(rb1m_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "rb1_description")
set(rb1m_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(rb1m_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(rb1m_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "rb1_description")
set(rb1m_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "rb1_description")
set(rb1m_moveit_config_TEST_DEPENDS )
set(rb1m_moveit_config_DOC_DEPENDS )
set(rb1m_moveit_config_URL_WEBSITE "http://moveit.ros.org/")
set(rb1m_moveit_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(rb1m_moveit_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(rb1m_moveit_config_DEPRECATED "")