set(_CATKIN_CURRENT_PACKAGE "rb1_arm_joystick")
set(rb1_arm_joystick_VERSION "0.0.0")
set(rb1_arm_joystick_MAINTAINER "Robotnik <info@robotnik.es>")
set(rb1_arm_joystick_PACKAGE_FORMAT "1")
set(rb1_arm_joystick_BUILD_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "message_generation")
set(rb1_arm_joystick_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_runtime" "roscpp" "sensor_msgs")
set(rb1_arm_joystick_BUILDTOOL_DEPENDS "catkin")
set(rb1_arm_joystick_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_arm_joystick_EXEC_DEPENDS "geometry_msgs" "message_runtime" "roscpp" "sensor_msgs")
set(rb1_arm_joystick_RUN_DEPENDS "geometry_msgs" "message_runtime" "roscpp" "sensor_msgs")
set(rb1_arm_joystick_TEST_DEPENDS )
set(rb1_arm_joystick_DOC_DEPENDS )
set(rb1_arm_joystick_URL_WEBSITE "")
set(rb1_arm_joystick_URL_BUGTRACKER "")
set(rb1_arm_joystick_URL_REPOSITORY "")
set(rb1_arm_joystick_DEPRECATED "")