set(_CATKIN_CURRENT_PACKAGE "mico_common")
set(mico_common_VERSION "1.0.0")
set(mico_common_MAINTAINER "Robotnik <info@robotnik.es>")
set(mico_common_PACKAGE_FORMAT "1")
set(mico_common_BUILD_DEPENDS )
set(mico_common_BUILD_EXPORT_DEPENDS "mico_description" "mico_moveit_config")
set(mico_common_BUILDTOOL_DEPENDS "catkin")
set(mico_common_BUILDTOOL_EXPORT_DEPENDS )
set(mico_common_EXEC_DEPENDS "mico_description" "mico_moveit_config")
set(mico_common_RUN_DEPENDS "mico_description" "mico_moveit_config")
set(mico_common_TEST_DEPENDS )
set(mico_common_DOC_DEPENDS )
set(mico_common_URL_WEBSITE "http://ros.org/wiki/mico_common")
set(mico_common_URL_BUGTRACKER "https://github.com/RobotnikAutomation/mico_common/issues")
set(mico_common_URL_REPOSITORY "")
set(mico_common_DEPRECATED "")