set(_CATKIN_CURRENT_PACKAGE "rb1_arm_description")
set(rb1_arm_description_VERSION "0.0.0")
set(rb1_arm_description_MAINTAINER "Robotnik <infol@robotnik.es>")
set(rb1_arm_description_PACKAGE_FORMAT "1")
set(rb1_arm_description_BUILD_DEPENDS "roscpp" "std_msgs" "std_srvs" "tf")
set(rb1_arm_description_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(rb1_arm_description_BUILDTOOL_DEPENDS "catkin")
set(rb1_arm_description_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_arm_description_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(rb1_arm_description_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(rb1_arm_description_TEST_DEPENDS )
set(rb1_arm_description_DOC_DEPENDS )
set(rb1_arm_description_URL_WEBSITE "")
set(rb1_arm_description_URL_BUGTRACKER "")
set(rb1_arm_description_URL_REPOSITORY "")
set(rb1_arm_description_DEPRECATED "")