
j1_torso_controller:
  type: effort_controllers/JointPositionController
  joint: torso_slider_joint
  pid: {p: 1000.0, i: 1.0, d: 200.0}

j1_head_controller:
  type: effort_controllers/JointPositionController
  joint: head_pan_joint
  pid: {p: 100.0, i: 0.01, d: 50.0}

j2_head_controller:
  type: effort_controllers/JointPositionController
  joint: head_tilt_joint
  pid: {p: 100.0, i: 0.01, d: 50.0}

joint_read_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
