set(_CATKIN_CURRENT_PACKAGE "rb1_arm_gazebo")
set(rb1_arm_gazebo_VERSION "0.0.0")
set(rb1_arm_gazebo_MAINTAINER "Robotnik <info@robotnik.es>")
set(rb1_arm_gazebo_PACKAGE_FORMAT "1")
set(rb1_arm_gazebo_BUILD_DEPENDS "rb1_arm_control" "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "tf")
set(rb1_arm_gazebo_BUILD_EXPORT_DEPENDS "rb1_arm_control" "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "tf")
set(rb1_arm_gazebo_BUILDTOOL_DEPENDS "catkin")
set(rb1_arm_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_arm_gazebo_EXEC_DEPENDS "rb1_arm_control" "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "tf")
set(rb1_arm_gazebo_RUN_DEPENDS "rb1_arm_control" "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "tf")
set(rb1_arm_gazebo_TEST_DEPENDS )
set(rb1_arm_gazebo_DOC_DEPENDS )
set(rb1_arm_gazebo_URL_WEBSITE "")
set(rb1_arm_gazebo_URL_BUGTRACKER "")
set(rb1_arm_gazebo_URL_REPOSITORY "")
set(rb1_arm_gazebo_DEPRECATED "")