set(_CATKIN_CURRENT_PACKAGE "mico_pad")
set(mico_pad_VERSION "0.0.0")
set(mico_pad_MAINTAINER "trurl <info@robotnik.es>")
set(mico_pad_PACKAGE_FORMAT "1")
set(mico_pad_BUILD_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "kinova_msgs" "message_generation" "actionlib")
set(mico_pad_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "kinova_msgs" "message_runtime" "actionlib")
set(mico_pad_BUILDTOOL_DEPENDS "catkin")
set(mico_pad_BUILDTOOL_EXPORT_DEPENDS )
set(mico_pad_EXEC_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "kinova_msgs" "message_runtime" "actionlib")
set(mico_pad_RUN_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "kinova_msgs" "message_runtime" "actionlib")
set(mico_pad_TEST_DEPENDS )
set(mico_pad_DOC_DEPENDS )
set(mico_pad_URL_WEBSITE "")
set(mico_pad_URL_BUGTRACKER "")
set(mico_pad_URL_REPOSITORY "")
set(mico_pad_DEPRECATED "")