set(_CATKIN_CURRENT_PACKAGE "rb1_sim_bringup")
set(rb1_sim_bringup_VERSION "0.1.0")
set(rb1_sim_bringup_MAINTAINER "Román Navarro <rnavarro@robotnik.es>")
set(rb1_sim_bringup_PACKAGE_FORMAT "1")
set(rb1_sim_bringup_BUILD_DEPENDS )
set(rb1_sim_bringup_BUILD_EXPORT_DEPENDS "robotnik_trajectory_control")
set(rb1_sim_bringup_BUILDTOOL_DEPENDS "catkin")
set(rb1_sim_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_sim_bringup_EXEC_DEPENDS "robotnik_trajectory_control")
set(rb1_sim_bringup_RUN_DEPENDS "robotnik_trajectory_control")
set(rb1_sim_bringup_TEST_DEPENDS )
set(rb1_sim_bringup_DOC_DEPENDS )
set(rb1_sim_bringup_URL_WEBSITE "")
set(rb1_sim_bringup_URL_BUGTRACKER "")
set(rb1_sim_bringup_URL_REPOSITORY "")
set(rb1_sim_bringup_DEPRECATED "")