set(_CATKIN_CURRENT_PACKAGE "rb1_arm_control")
set(rb1_arm_control_VERSION "0.0.0")
set(rb1_arm_control_MAINTAINER "Robotnik <info@robotnik.es>")
set(rb1_arm_control_PACKAGE_FORMAT "1")
set(rb1_arm_control_BUILD_DEPENDS "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "controller_manager" "controller_manager_msgs")
set(rb1_arm_control_BUILD_EXPORT_DEPENDS "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "controller_manager" "controller_manager_msgs")
set(rb1_arm_control_BUILDTOOL_DEPENDS "catkin")
set(rb1_arm_control_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_arm_control_EXEC_DEPENDS "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "controller_manager" "controller_manager_msgs")
set(rb1_arm_control_RUN_DEPENDS "rb1_arm_description" "rb1_arm_joystick" "std_msgs" "std_srvs" "controller_manager" "controller_manager_msgs")
set(rb1_arm_control_TEST_DEPENDS )
set(rb1_arm_control_DOC_DEPENDS )
set(rb1_arm_control_URL_WEBSITE "")
set(rb1_arm_control_URL_BUGTRACKER "")
set(rb1_arm_control_URL_REPOSITORY "")
set(rb1_arm_control_DEPRECATED "")