// Generated by gencpp from file rb1_base_pad/enable_disable_padResponse.msg
// DO NOT EDIT!


#ifndef RB1_BASE_PAD_MESSAGE_ENABLE_DISABLE_PADRESPONSE_H
#define RB1_BASE_PAD_MESSAGE_ENABLE_DISABLE_PADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rb1_base_pad
{
template <class ContainerAllocator>
struct enable_disable_padResponse_
{
  typedef enable_disable_padResponse_<ContainerAllocator> Type;

  enable_disable_padResponse_()
    : ret(false)  {
    }
  enable_disable_padResponse_(const ContainerAllocator& _alloc)
    : ret(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> const> ConstPtr;

}; // struct enable_disable_padResponse_

typedef ::rb1_base_pad::enable_disable_padResponse_<std::allocator<void> > enable_disable_padResponse;

typedef boost::shared_ptr< ::rb1_base_pad::enable_disable_padResponse > enable_disable_padResponsePtr;
typedef boost::shared_ptr< ::rb1_base_pad::enable_disable_padResponse const> enable_disable_padResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator1> & lhs, const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator1> & lhs, const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rb1_base_pad

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb1_base_pad/enable_disable_padResponse";
  }

  static const char* value(const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ret \n"
"\n"
;
  }

  static const char* value(const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enable_disable_padResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rb1_base_pad::enable_disable_padResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RB1_BASE_PAD_MESSAGE_ENABLE_DISABLE_PADRESPONSE_H
