set(_CATKIN_CURRENT_PACKAGE "rb1_base_sim")
set(rb1_base_sim_VERSION "1.12.0")
set(rb1_base_sim_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Angel Soriano <asoriano@robotnik.es>, Álvaro Villena <avillena@robotnik.es>, David Redó <dredo@robotnik.es>, Alejandro Arnal <aarnal@robotnik.es>, Marc Bosch <mbosch@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(rb1_base_sim_PACKAGE_FORMAT "1")
set(rb1_base_sim_BUILD_DEPENDS )
set(rb1_base_sim_BUILD_EXPORT_DEPENDS "rb1_base_gazebo" "rb1_base_sim_bringup")
set(rb1_base_sim_BUILDTOOL_DEPENDS "catkin")
set(rb1_base_sim_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_base_sim_EXEC_DEPENDS "rb1_base_gazebo" "rb1_base_sim_bringup")
set(rb1_base_sim_RUN_DEPENDS "rb1_base_gazebo" "rb1_base_sim_bringup")
set(rb1_base_sim_TEST_DEPENDS )
set(rb1_base_sim_DOC_DEPENDS )
set(rb1_base_sim_URL_WEBSITE "http://wiki.ros.org/rb1_base_sim")
set(rb1_base_sim_URL_BUGTRACKER "https://github.com/RobotnikAutomation/rb1_base_sim/issues")
set(rb1_base_sim_URL_REPOSITORY "https://github.com/RobotnikAutomation/rb1_base_sim")
set(rb1_base_sim_DEPRECATED "")