set(_CATKIN_CURRENT_PACKAGE "rb1_control")
set(rb1_control_VERSION "0.0.0")
set(rb1_control_MAINTAINER "Robotnik <info@robotnik.es>")
set(rb1_control_PACKAGE_FORMAT "1")
set(rb1_control_BUILD_DEPENDS "robot_state_publisher" "controller_manager" "controller_manager_msgs")
set(rb1_control_BUILD_EXPORT_DEPENDS "robot_state_publisher" "controller_manager" "controller_manager_msgs")
set(rb1_control_BUILDTOOL_DEPENDS "catkin")
set(rb1_control_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_control_EXEC_DEPENDS "robot_state_publisher" "controller_manager" "controller_manager_msgs")
set(rb1_control_RUN_DEPENDS "robot_state_publisher" "controller_manager" "controller_manager_msgs")
set(rb1_control_TEST_DEPENDS )
set(rb1_control_DOC_DEPENDS )
set(rb1_control_URL_WEBSITE "")
set(rb1_control_URL_BUGTRACKER "")
set(rb1_control_URL_REPOSITORY "")
set(rb1_control_DEPRECATED "")