set(_CATKIN_CURRENT_PACKAGE "rb1_base_gazebo")
set(rb1_base_gazebo_VERSION "1.12.0")
set(rb1_base_gazebo_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Roman Navarro Garcia <rnavarro@robotnik.es>")
set(rb1_base_gazebo_PACKAGE_FORMAT "1")
set(rb1_base_gazebo_BUILD_DEPENDS "gazebo_ros" "gazebo_ros_control" "rb1_base_control" "rb1_base_description" "rb1_base_pad" "std_msgs" "std_srvs" "tf" "diff_drive_controller")
set(rb1_base_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros" "gazebo_ros_control" "rb1_base_control" "rb1_base_description" "rb1_base_pad" "std_msgs" "std_srvs" "tf" "diff_drive_controller" "rviz")
set(rb1_base_gazebo_BUILDTOOL_DEPENDS "catkin")
set(rb1_base_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(rb1_base_gazebo_EXEC_DEPENDS "gazebo_ros" "gazebo_ros_control" "rb1_base_control" "rb1_base_description" "rb1_base_pad" "std_msgs" "std_srvs" "tf" "diff_drive_controller" "rviz")
set(rb1_base_gazebo_RUN_DEPENDS "gazebo_ros" "gazebo_ros_control" "rb1_base_control" "rb1_base_description" "rb1_base_pad" "std_msgs" "std_srvs" "tf" "diff_drive_controller" "rviz")
set(rb1_base_gazebo_TEST_DEPENDS )
set(rb1_base_gazebo_DOC_DEPENDS )
set(rb1_base_gazebo_URL_WEBSITE "http://wiki.ros.org/rb1_base_gazebo")
set(rb1_base_gazebo_URL_BUGTRACKER "https://github.com/RobotnikAutomation/rb1_base_sim/issues")
set(rb1_base_gazebo_URL_REPOSITORY "https://github.com/RobotnikAutomation/rb1_base_sim")
set(rb1_base_gazebo_DEPRECATED "")