set(_CATKIN_CURRENT_PACKAGE "basicmodutil_pkg")
set(basicmodutil_pkg_VERSION "0.0.0")
set(basicmodutil_pkg_MAINTAINER "sergio <sergio@todo.todo>")
set(basicmodutil_pkg_PACKAGE_FORMAT "2")
set(basicmodutil_pkg_BUILD_DEPENDS "roscpp" "roslib" "rospy" "std_msgs" "rospy_message_converter")
set(basicmodutil_pkg_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "rospy" "std_msgs" "rospy_message_converter")
set(basicmodutil_pkg_BUILDTOOL_DEPENDS "catkin")
set(basicmodutil_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(basicmodutil_pkg_EXEC_DEPENDS "roscpp" "roslib" "rospy" "std_msgs" "rospy_message_converter")
set(basicmodutil_pkg_RUN_DEPENDS "roscpp" "roslib" "rospy" "std_msgs" "rospy_message_converter")
set(basicmodutil_pkg_TEST_DEPENDS )
set(basicmodutil_pkg_DOC_DEPENDS )
set(basicmodutil_pkg_URL_WEBSITE "")
set(basicmodutil_pkg_URL_BUGTRACKER "")
set(basicmodutil_pkg_URL_REPOSITORY "")
set(basicmodutil_pkg_DEPRECATED "")